set(_CATKIN_CURRENT_PACKAGE "manager_msgs")
set(manager_msgs_VERSION "0.0.0")
set(manager_msgs_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(manager_msgs_PACKAGE_FORMAT "2")
set(manager_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(manager_msgs_BUILD_EXPORT_DEPENDS )
set(manager_msgs_BUILDTOOL_DEPENDS "catkin")
set(manager_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(manager_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(manager_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(manager_msgs_TEST_DEPENDS )
set(manager_msgs_DOC_DEPENDS )
set(manager_msgs_URL_WEBSITE "")
set(manager_msgs_URL_BUGTRACKER "")
set(manager_msgs_URL_REPOSITORY "")
set(manager_msgs_DEPRECATED "")