// Generated by gencpp from file manager_msgs/Plan.msg
// DO NOT EDIT!


#ifndef MANAGER_MSGS_MESSAGE_PLAN_H
#define MANAGER_MSGS_MESSAGE_PLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <manager_msgs/Pose.h>
#include <manager_msgs/Type.h>

namespace manager_msgs
{
template <class ContainerAllocator>
struct Plan_
{
  typedef Plan_<ContainerAllocator> Type;

  Plan_()
    : header()
    , id(0)
    , pose()
    , type()
    , action_id(0)  {
    }
  Plan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , pose(_alloc)
    , type(_alloc)
    , action_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _id_type;
  _id_type id;

   typedef  ::manager_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::manager_msgs::Type_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef int64_t _action_id_type;
  _action_id_type action_id;





  typedef boost::shared_ptr< ::manager_msgs::Plan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manager_msgs::Plan_<ContainerAllocator> const> ConstPtr;

}; // struct Plan_

typedef ::manager_msgs::Plan_<std::allocator<void> > Plan;

typedef boost::shared_ptr< ::manager_msgs::Plan > PlanPtr;
typedef boost::shared_ptr< ::manager_msgs::Plan const> PlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manager_msgs::Plan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manager_msgs::Plan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manager_msgs::Plan_<ContainerAllocator1> & lhs, const ::manager_msgs::Plan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.type == rhs.type &&
    lhs.action_id == rhs.action_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manager_msgs::Plan_<ContainerAllocator1> & lhs, const ::manager_msgs::Plan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manager_msgs::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manager_msgs::Plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager_msgs::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager_msgs::Plan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager_msgs::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager_msgs::Plan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manager_msgs::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5fbb5f4433cdc05c071d9eb0bd58618";
  }

  static const char* value(const ::manager_msgs::Plan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5fbb5f4433cdc05ULL;
  static const uint64_t static_value2 = 0xc071d9eb0bd58618ULL;
};

template<class ContainerAllocator>
struct DataType< ::manager_msgs::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manager_msgs/Plan";
  }

  static const char* value(const ::manager_msgs::Plan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manager_msgs::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int64 id\n"
"Pose pose\n"
"Type type\n"
"int64 action_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: manager_msgs/Pose\n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: manager_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: manager_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: manager_msgs/Type\n"
"uint8 STOP = 0\n"
"uint8 PAUSE = 1\n"
"uint8 MOVE = 2\n"
"uint8 ACTION = 3\n"
"uint8 status\n"
;
  }

  static const char* value(const ::manager_msgs::Plan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manager_msgs::Plan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.type);
      stream.next(m.action_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Plan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manager_msgs::Plan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manager_msgs::Plan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::manager_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "type: ";
    s << std::endl;
    Printer< ::manager_msgs::Type_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    s << indent << "action_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.action_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGER_MSGS_MESSAGE_PLAN_H
