// Generated by gencpp from file manager_msgs/Status.msg
// DO NOT EDIT!


#ifndef MANAGER_MSGS_MESSAGE_STATUS_H
#define MANAGER_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace manager_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , status(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(CANCEL)
  #undef CANCEL
#endif
#if defined(_WIN32) && defined(CONTINUE)
  #undef CONTINUE
#endif
#if defined(_WIN32) && defined(DELETEALL)
  #undef DELETEALL
#endif
#if defined(_WIN32) && defined(MAPSAVE)
  #undef MAPSAVE
#endif

  enum {
    STOP = 0u,
    START = 1u,
    CANCEL = 2u,
    CONTINUE = 3u,
    DELETEALL = 4u,
    MAPSAVE = 5u,
  };


  typedef boost::shared_ptr< ::manager_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manager_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::manager_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::manager_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::manager_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manager_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manager_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manager_msgs::Status_<ContainerAllocator1> & lhs, const ::manager_msgs::Status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manager_msgs::Status_<ContainerAllocator1> & lhs, const ::manager_msgs::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manager_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manager_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manager_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "593a64654818a9bdd4d99c681cbdf720";
  }

  static const char* value(const ::manager_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x593a64654818a9bdULL;
  static const uint64_t static_value2 = 0xd4d99c681cbdf720ULL;
};

template<class ContainerAllocator>
struct DataType< ::manager_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manager_msgs/Status";
  }

  static const char* value(const ::manager_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manager_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 STOP = 0\n"
"uint8 START = 1\n"
"uint8 CANCEL = 2\n"
"uint8 CONTINUE = 3\n"
"uint8 DELETEALL = 4\n"
"uint8 MAPSAVE = 5\n"
"uint8 status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::manager_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manager_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manager_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manager_msgs::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGER_MSGS_MESSAGE_STATUS_H
