// Generated by gencpp from file manager_msgs/Type.msg
// DO NOT EDIT!


#ifndef MANAGER_MSGS_MESSAGE_TYPE_H
#define MANAGER_MSGS_MESSAGE_TYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manager_msgs
{
template <class ContainerAllocator>
struct Type_
{
  typedef Type_<ContainerAllocator> Type;

  Type_()
    : status(0)  {
    }
  Type_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(MOVE)
  #undef MOVE
#endif
#if defined(_WIN32) && defined(ACTION)
  #undef ACTION
#endif

  enum {
    STOP = 0u,
    PAUSE = 1u,
    MOVE = 2u,
    ACTION = 3u,
  };


  typedef boost::shared_ptr< ::manager_msgs::Type_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manager_msgs::Type_<ContainerAllocator> const> ConstPtr;

}; // struct Type_

typedef ::manager_msgs::Type_<std::allocator<void> > Type;

typedef boost::shared_ptr< ::manager_msgs::Type > TypePtr;
typedef boost::shared_ptr< ::manager_msgs::Type const> TypeConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manager_msgs::Type_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manager_msgs::Type_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manager_msgs::Type_<ContainerAllocator1> & lhs, const ::manager_msgs::Type_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manager_msgs::Type_<ContainerAllocator1> & lhs, const ::manager_msgs::Type_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manager_msgs::Type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manager_msgs::Type_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager_msgs::Type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager_msgs::Type_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager_msgs::Type_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager_msgs::Type_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manager_msgs::Type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41aa323be3c944320ef6a43a04b1d136";
  }

  static const char* value(const ::manager_msgs::Type_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41aa323be3c94432ULL;
  static const uint64_t static_value2 = 0x0ef6a43a04b1d136ULL;
};

template<class ContainerAllocator>
struct DataType< ::manager_msgs::Type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manager_msgs/Type";
  }

  static const char* value(const ::manager_msgs::Type_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manager_msgs::Type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STOP = 0\n"
"uint8 PAUSE = 1\n"
"uint8 MOVE = 2\n"
"uint8 ACTION = 3\n"
"uint8 status\n"
;
  }

  static const char* value(const ::manager_msgs::Type_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manager_msgs::Type_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Type_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manager_msgs::Type_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manager_msgs::Type_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGER_MSGS_MESSAGE_TYPE_H
