set(_CATKIN_CURRENT_PACKAGE "manager")
set(manager_VERSION "0.0.0")
set(manager_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(manager_PACKAGE_FORMAT "2")
set(manager_BUILD_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "move_base_msgs" "actionlib_msgs" "nav_msgs" "manager_msgs")
set(manager_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "move_base_msgs" "actionlib_msgs" "nav_msgs" "manager_msgs")
set(manager_BUILDTOOL_DEPENDS "catkin")
set(manager_BUILDTOOL_EXPORT_DEPENDS )
set(manager_EXEC_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "move_base_msgs" "actionlib_msgs" "nav_msgs" "manager_msgs")
set(manager_RUN_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "move_base_msgs" "actionlib_msgs" "nav_msgs" "manager_msgs")
set(manager_TEST_DEPENDS )
set(manager_DOC_DEPENDS )
set(manager_URL_WEBSITE "")
set(manager_URL_BUGTRACKER "")
set(manager_URL_REPOSITORY "")
set(manager_DEPRECATED "")