set(_CATKIN_CURRENT_PACKAGE "simulation")
set(simulation_VERSION "0.0.0")
set(simulation_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(simulation_PACKAGE_FORMAT "2")
set(simulation_BUILD_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(simulation_BUILD_EXPORT_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(simulation_BUILDTOOL_DEPENDS "catkin")
set(simulation_BUILDTOOL_EXPORT_DEPENDS )
set(simulation_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(simulation_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(simulation_TEST_DEPENDS )
set(simulation_DOC_DEPENDS )
set(simulation_URL_WEBSITE "")
set(simulation_URL_BUGTRACKER "")
set(simulation_URL_REPOSITORY "")
set(simulation_DEPRECATED "")